trainFile: "D:/AIH/LID-master/trainInput.txt"
trainDir: "D:/AIH/LID-master/Train/"
testFile: "D:/AIH/LID-master/testInput.txt"
testDir: "D:/AIH/LID-master/Test/"

batchSize: 5
valBatchSize: 8
numWorkers: 4

inShape: [1,129,501]
outClasses: 5
labelNos: [0,1,2,3,4]
labelNames: ['HIN','MAR','TEL','TAM','GUJ']
rnnHiddenSize: 256
rnnLayers: 2

model: 'CRNN'
optimizer: 'Adam'
learningRate: 0.01
iterations: 20

segmentLength: 10
samplesPerSec: 50

train: 1
modelLoc: 'D:/AIH/LID-master/Models/'
test: 0

runName: 'TrialRun'