trainFile: "/home/aih04/LID/Augmented_trainInput.txt"
trainDir: "/home/aih04/dataset/Augmented_train/"
testFile: "/home/aih04/LID/testInput.txt"
testDir: "/home/aih04/dataset/Augmented_train/"

batchSize: 64
valBatchSize: 64
numWorkers: 4

inShape: [1,129,501]
outClasses: 5
labelNos: [0,1,2,3,4]
labelNames: ['HIN','MAR','TEL','TAM','GUJ']
rnnHiddenSize: 256
rnnLayers: 2

fcHiddenSzie: 256
fcLayers: 2
cnnActivation: 'relu'

model: 'CRNN'
optimizer: 'Adam'
learningRate: 0.01
iterations: 20

segmentLength: 10
samplesPerSec: 50

train: 1
modelLoc: '/home/aih04/LID/Models/'
test: 0

runName: 'TrialRun'